name: Lint

on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
      - uses: psf/black@stable
        with:
          args: ". --check"
      - uses: isort/isort-action@v1
        with:
            sort-paths: "./blm"
